### ISSUE TITLE
Can I connect 8 MAX31865 to raspberry Pi using Node-RED?

### ISSUE THREAD

**Issue by dhia333** [MelvinRook/node-red-contrib-pi-max31865#4]
Hi I'm new to raspberry Pi and node-RED and I need to connect 8 Pt 100 sensors to Raspberry Pi using 8 MAX 31865 chips (with SPI protocol) and MAX 31865 node. Does this node let you use 8 GPIO pins to select one chip at a time instead of the default CE0 and CE1 ??. These default SPI select pins are limited to tow devices only.

**Comment by MelvinRook** [comment]
Yeah, that should be possible. You can enable additional SPI pins with a `dtoverlay` configuration as described on the following page: https://pinout.xyz/pinout/spi

I would suggest to connect the boards step by step.

Then using `ls -l /dev/spidev*` should give you an indication of the bus digits. Although here I am in doubt if they would share the same bus digits and you'll need the pin assignment option. I only have two boards myself, so cannot test a setup with more than two boards at the moment. Will try to simulate something.
