### ISSUE TITLE
Implement node-red-contrib-pi-max31865 on flow to debug the incomming temperature

### ISSUE THREAD

**Issue by ParzivalIron** [MelvinRook/node-red-contrib-pi-max31865#5]
Hi there,

I'm new to using node red. I use the Raspi and a max31865 adapter for a pt100 with two wires. I configured the connection type for two wires correctly on the max31865 board and also connected the spi pins between the board and the raspi. 

Pi 3V3 to sensor VIN
Pi GND to sensor GND
Pi SPI0 MOSI to sensor SDI
Pi SPI0 MISO to sensor SDO
Pi SPI0 SCLK to sensor CLK
Pi SPI0 CE0 to sensor CS

I installed the node-red-contrib-pi-max31865 on the Raspi together with node red. Now I implement the "max31865" module in the flow and connect it to a "debug" node.
The spi interface is enabled.

Actually config at the implemented "max31865" node on my test flow (i configured it manually):
bus: 0
device: 0
rtd: 100
reference resistance: 430
wires: 2

![Flow](https://user-images.githubusercontent.com/97592053/149126964-d577c436-ed7f-4498-90e1-b377dbd6c724.PNG)

I don't know, if this workflow in node red correct? 
What i have to do, that i get the temparture in my "debug" Chanel.

I would be happy if someone could help me with the handling :)

**Comment by ParzivalIron** [comment]
Sorry, I made it to trigger the module correct with the help of the existing request. 
Now it works. :)

https://github.com/MelvinRook/node-red-contrib-pi-max31865/issues/1

Thanks anyway ;)

**Comment by MelvinRook** [comment]
Awesome that you got it working. Enjoy! :-)
